Models/Categories.cs
using System.ComponentModel.DataAnnotations;

namespace EtkinlikProjesi.Models
{
    public class Categories
    {
        [Key]
        public int Id { get; set; }
        public string CategoryName { get; set; }

    }
}

Models/Concrete/User.cs
using System.ComponentModel.DataAnnotations;

namespace EtkinlikProjesi.Models.Concrete
{
    public class User
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }

    }
}

Models/ErrorViewModel.cs
namespace EtkinlikProjesi.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace EtkinlikProjesi.Models
{
    public class User
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }

    }
}

Controllers/CategoriesController.cs
using EtkinlikProjesi.Data;
using EtkinlikProjesi.Models;
using Microsoft.AspNetCore.Mvc;

namespace EtkinlikProjesi.Controllers
{
    public class CategoriesController : Controller
    {

        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Categories> categories = _context.Categories.ToList();
            return View(categories);

        }
    }
}

Controllers/HomeController.cs
using EtkinlikProjesi.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EtkinlikProjesi.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UserController.cs
using EtkinlikProjesi.Data;
using Microsoft.AspNetCore.Mvc;

namespace EtkinlikProjesi.Controllers
{
    public class UserController : Controller
    {

        private readonly ApplicationDbContext _context;
        public UserController(ApplicationDbContext context)
        {
            _context = context;   
        }



        public IActionResult Index()
        {

            return View();
        }
    }
}

Views/Categories/Index.cshtml
@model IEnumerable<Categories>

 
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light"></h1>
            <p class="lead text-body-secondary">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p
        </div>
    </div>
</section

<div class="album py-5 bg-body-tertiary">
    <div class="container">
       
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                @foreach (var item in Model)
                {
                    <a href="your-link-here" style="text-decoration: none; color: inherit;">
                        <div class="col">
                    <div class="card shadow-sm">
                         <img src="https://img.freepik.com/free-photo/view-3d-cinema-theatre-room_23-2151067056.jpg?t=st=1722257854~exp=1722261454~hmac=ca6f4f3c72e085022d289d5cc37669797cacf87314845aac25c0d733f85c762c&w=900" alt="Cinque Terre" width="100%" height="300">
                        <div class="card-body">
                            <h1 style="color:darkorange;">@item.CategoryName</h1>
                            <p class="card-text"style="color:grey">Heyecanını bizimle yaşa!</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                   <!-- <button type="button" class="btn btn-sm btn-outline-secondary"> </button> --> 
                                  
                                </div>
                                <small class="text-body-secondary">9 mins</small>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            }
        </div>   
        
       
    </div>   
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EtkinlikProjesi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EtkinlikProjesi.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EtkinlikProjesi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EtkinlikProjesi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/User/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>User Page</h1>